routes/web.php
<?php

// use App\Http\Controllers\UserController;
// use Illuminate\Support\Facades\Route;



//todos

    Route::resource('/todo', 'TodoController');

    Route::put('/todos/{todo}/complete', 'TodoController@complete')->name('todo.complete');

    Route::delete('/todos/{todo}/incomplete', 'TodoController@incomplete')->name('todo.incomplete');

// Route::get('/todos', 'TodoController@index')->name('todo.index');

// Route::get('/todos/create', 'TodoController@create');

// Route::post('/todos/create', 'TodoController@store');

// Route::get('/todos/{todo}/edit', 'TodoController@edit');

// Route::patch('/todos/{todo}/update', 'TodoController@update')->name('todo.update');

// Route::put('/todos/{todo}/delete', 'TodoController@delete')->name('todo.delete');

// Route::put('/todos/{todo}/complete', 'TodoController@complete')->name('todo.complete');

// Route::delete('/todos/{todo}/incomplete', 'TodoController@incomplete')->name('todo.incomplete');


Route::get('/', function () {
    return view('welcome');
});

//user
Route::get('/user', 'UserController@index');

Route::post('/upload', 'UserController@uploadAvatar');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Todo.php
<?php

namespace App;

use App\Step;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    protected $fillable = ['title', 'completed', 'user_id', 'description'];

    public function steps()
    {
        return $this->hasMany(Step::class);
}
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Todo;
use App\Step;
use App\Http\Requests\TodoCreateRequest;

class TodoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $todos = auth()->user()->todos->sortBy('completed');
        return view('todos.index', compact('todos'));
    }

    public function create()
    {
        return view('todos.create');
    }

    public function show(Todo $todo)
    {
        return view('todos.show', compact('todo'));
    }

    public function store(TodoCreateRequest $request)
    {
        $todo = auth()->user()->todos()->create($request->all());
        if($request->step){
            foreach ($request->step as $step ) {
                $todo->steps()->create(['name' => $step]);
            }
        }
        return redirect(route('todo.index'))->with('message', 'Todo Created Successfully');
    }

    public function edit(Todo $todo)
    {
        return view('todos.edit', compact('todo'));
    }

    public function update(TodoCreateRequest $request, Todo $todo)
    {
        $todo->update(['title' => $request->title]);
        if($request->stepName){
            foreach ($request->stepName as $key => $value ) {
                $id = $request->stepId[$key];
                if(!$id){
                    $todo->steps()->create(['name' => $value]);
                }else{
                    $step = Step::find($id);
                    $step->update(['name' => $value]);
                }
            }
        }
        return redirect(route('todo.index'))->with('message', 'Updated!');
    }

    public function complete(Todo $todo)
    {
        $todo->update(['completed' => true]);
        return redirect()->back()->with('message', 'Task Marked as completed!');
    }

    public function incomplete(Todo $todo)
    {
        $todo->update(['completed' => false]);
        return redirect()->back()->with('message', 'Task Marked as Incompleted!');
    }

    public function destroy(Todo $todo)
    {
        $todo->steps->each->delete();
        $todo->delete();
        return redirect()->back()->with('message', 'Task Deleted!');
    }
}

resources/views/todos/complete-button.blade.php
@if($todo->completed)

     <span class="fas fa-check text-green-400 cursor-pointer px-2" onclick="event.preventDefault();
            document.getElementById('form-incomplete-{{$todo->id}}').submit()" ></span>

        <form style="display:none" id="{{'form-incomplete-'.$todo->id}}" method="post" action="{{route('todo.incomplete',$todo->id)}}">
         @csrf
        @method('delete')
        </form>
            @else
        <span onclick="event.preventDefault();
             document.getElementById('form-complete-{{$todo->id}}').submit()"
            class="fas fa-check text-gray-300 cursor-pointer px-2" ></span>

        <form style="display:none" id="{{'form-complete-'.$todo->id}}" method="post" action="{{route('todo.complete',$todo->id)}}">
            @csrf
            @method('put')
            </form>
@endif

resources/views/todos/create.blade.php
@extends('todos.layout')

@section('content')
<div class="flex justify-between border-b pb-4 px-4">
    <h1 class="text-2xl pb-4">What next you need To-DO</h1>
    <a href="{{route('todo.index')}}" class="mx-5 py-2 text-gray-400 cursor-pointer text-white">
        <span class="fas fa-arrow-left" ></span>
    </a>
</div>

<x-alert />
<form method="post" action="{{route('todo.store')}}" class="py-5">
    @csrf
    <div class="py-1">
        <input type="text" name="title" class="py-2 px-2 border rounded" placeholder="Title" />
    </div>
    <div class="py-1">
        <textarea name="description" class="p-2 rounded border" placeholder="Description"></textarea>
    </div>

    <div class="py-2">
        @livewire('step')
    </div>
    <div class="py-1">
        <input type="submit" value="Create" class="p-2 border rounded" />
    </div>
</form>
@endsection

resources/views/todos/edit.blade.php
@extends('todos.layout')

@section('content')
<div class="flex justify-between border-b pb-4 px-4">
    <h1 class="text-2xl pb-4">Update this todo list</h1>
    <a href="{{route('todo.index')}}" class="mx-5 py-2 text-gray-400 cursor-pointer text-white">
        <span class="fas fa-arrow-left"></span>
    </a>
</div>

<x-alert />
<form method="post" action="{{route('todo.update',$todo->id)}}" class="py-5">
    @csrf
    @method('patch')
    <div class="py-1">
        <input type="text" name="title" value="{{$todo->title}}" class="py-2 px-2 border rounded" placeholder="Title" />
    </div>
    <div class="py-1">
        <textarea name="description" class="p-2 rounded border" placeholder="Description">{{$todo->description}}</textarea>
    </div>
    <div class="py-2">
        @livewire('edit-step',['steps' => $todo->steps])
    </div>
    <div class="py-1">
        <input type="submit" value="Update" class="p-2 border rounded" />
    </div>


</form>

@endsection

resources/views/todos/index.blade.php
@extends('todos.layout')

@section('content')
<div class="flex justify-between border-b pb-4 px-4">
    <h1 class="text-2xl">All Your Todos</h1>
    <a href="{{route('todo.create')}}" class="mx-5 py-2 text-blue-400 cursor-pointer text-white">
<span class="fas fa-plus-circle" ></span>
</a>
</div>
        <ul class="my-5">
            <x-alert />
            @forelse($todos as $todo)
            <li class="flex justify-between p-2">
                <div>
                    @include('todos.complete-button')
                </div>

                @if($todo->completed)
                <p class="line-through">{{$todo->title}}</p>
                @else
                <a class="cursor-pointer" href="{{route('todo.show',$todo->id)}}">{{$todo->title}}</a>
                @endif

                <div>
                    <a href="{{route('todo.edit',$todo->id)}}" class="text-orange-400 cursor-pointer text-white">
                <span class="fas fa-pen px-2" ></span></a>

                <span class="fas fa-times text-red-500 px-2 cursor-pointer"
                onclick="event.preventDefault();
                        if(confirm('Are you really want to delete?')){
                            document.getElementById('form-delete-{{$todo->id}}')
                            .submit()
                        }"></span>
                <form style="display:none" id="{{'form-delete-'.$todo->id}}" method="post" action="{{route('todo.destroy',$todo->id)}}">
                    @csrf
                    @method('delete')
                </form>
                </div>
            </li>
            @empty
                        <p>No task available, create one.</p>
            @endforelse
        </ul>
@endsection

resources/views/todos/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    @livewireStyles
    <title>Todos</title>
</head>
<body>
    <div class="text-center flex justify-center pt-10">
        <div class="w-1/3 border border-gray-400 rounded py-4">
        @yield('content')
        </div>
    </div>

    @livewireScripts
</body>
</html>

resources/views/todos/show.blade.php
@extends('todos.layout')

@section('content')
<div class="flex justify-between border-b pb-4 px-4">
    <h1 class="text-2xl pb-4">{{$todo->title}}</h1>
    <a href="{{route('todo.index')}}" class="mx-5 py-2 text-gray-400 cursor-pointer text-white">
<span class="fas fa-arrow-left" ></span>
</a>
</div>
    <div>

        <div>
        <h3 class="text-lg">Description</h3>
            <p>{{$todo->description}}</p>
        </div>

@if($todo->steps->count() > 0)
        <div class="py-4">
        <h3 class="text-lg">Step for this task</h3>
        @foreach($todo->steps as $step)
        <p>{{$step->name}}</p>
        @endforeach
        </div>

        @endif
    </div>

@endsection